language: python
python: pypy3
before_install:
  - python --version
  - virtualenv --version
  - pip --version
  - uname -a
  - lsb_release -a
install:
  - pip install -U wheel setuptools tox cookiecutter bumpversion
  - virtualenv --version
  - tox --version
script:
  - pip install .
  - tox --sitepackages
