language: python
python: pypy3
before_install:
  - python --version
  - virtualenv --version
  - pip --version
  - uname -a
  - lsb_release -a
install:
  - pip install -U wheel setuptools tox cookiecutter bumpversion
  - virtualenv --version
  - tox --version
script:
  # - pip install .
  # - tox works fine even without skipinstall. It creates the environment and installs the package into it.
  # - rm -r .tox
  # - tox --recreate -vv --sitepackages
  - virtualenv env-without-site-packages
  - env-without-site-packages/bin/python -m setuptools --version
  - env-without-site-packages/bin/pip install .
  - virtualenv --system-site-packages env-with-site-packages
  - env-with-site-packages/bin/python -m setuptools --version
  - env-with-site-packages/bin/pip install . --no-build-isolation
  - env-with-site-packages/bin/pip install .

